spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    password: 12345
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  error:
    include-message: always

app:
  jwt:
    secret: java